FROM debian:trixie
RUN apt-get update && apt-get install -y --no-install-recommends build-essential cmake ninja-build pkg-config qt6-base-dev qt6-declarative-dev qt6-svg-dev liblayershellqtinterface-dev libkf6windowsystem-dev kwayland-dev libglib2.0-dev qt6-wayland qt6-svg-plugins qml6-module-qtquick qml6-module-qtquick-window qml6-module-qtquick-controls qml6-module-qtquick-layouts qml6-module-qtquick-templates qml6-module-qtqml-workerscript python3 dpkg-dev file kwin-wayland kwin-style-breeze dbus-x11 wayland-utils kscreen libgl1-mesa-dri
WORKDIR /build
CMD ["sh","-c","cmake -S /src -B /build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr && cmake --build /build -j4 && ctest --test-dir /build --output-on-failure && cd /build && cpack -G DEB"]
